### ISSUE TITLE
Null pointer errors for timers without stop or duration

### ISSUE THREAD

**Issue by jason0x43** [jason0x43/alfred-toggl#6]
Running "tgl timers" will generate errors like the following if there are time entries with neither a negative duration or a stop time:

```
2015/02/17 12:39:19 args: []string{"./alfred-toggl", "tell", "timers"}
2015/02/17 12:39:19 op: 'tell'
2015/02/17 12:39:19 keyword: 'timers'
2015/02/17 12:39:19 query: ''
2015/02/17 12:39:19 prefix: 'timers '
2015/02/17 12:39:19 skip: 'map[]'
2015/02/17 12:39:19 checking timers
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x17afd]

goroutine 1 [running]:
main.TimeEntryFilter.Items(0xc208057075, 0x7, 0x0, 0x0, 0xc2080c8000, 0xd, 0x10, 0x5b2a68, 0xc20800bb00)
    /Users/jason/Documents/Programming/go/src/github.com/jason0x43/alfred-toggl/time_entry.go:320 +0x49ad
main.(*TimeEntryFilter).Items(0x5049d8, 0xc208057075, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    <autogenerated>:22 +0xf8
github.com/jason0x43/go-alfred.(*Workflow).Run(0x4fc0c0, 0xc208091e80, 0x11, 0x11)
    /Users/jason/Documents/Programming/go/src/github.com/jason0x43/go-alfred/main.go:175 +0x168f
main.main()
    /Users/jason/Documents/Programming/go/src/github.com/jason0x43/alfred-toggl/main.go:77 +0x1114

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by jason0x43** [comment]
Release 1.1.2 fixes this.

**Comment by lrobeson** [comment]
Works! Thanks, look forward to using this workflow now! :)
